export const data = [
  {
    id: 1,
    img: require('../Assets/Foods/Biriyani.png'),
    text: 'Biriyani',
    link: 'albaik',
  },

  {
    id: 2,
    img: require('../Assets/Foods/Broast.png'),
    text: 'Broast',
    link: 'Malbar',
  },

  {
    id: 3,
    img: require('../Assets/Foods/burger.png'),
    text: 'Burger',
    link: 'farsa',
  },

  {
    id: 4,
    img: require('../Assets/Foods/butterchick.png'),
    text: 'Butter Chicken',
    link: 'Midway',
  },
  {
    id: 5,
    img: require('../Assets/Foods/french.png'),
    text: 'Fried Rice',
    link: 'Berry',
  },
  {
    id: 6,
    img: require('../Assets/Foods/chickenchilly.png'),
    text: 'Chicken Chilly',
    link: 'farsa',
  },
  {
    id: 7,
    img: require('../Assets/Foods/frenchfry.png'),
    text: 'French Fries',
    link: 'Malbar',
  },
  {
    id: 8,
    img: require('../Assets/Foods/idly.png'),
    text: 'Idly',
    link: 'albaik',
  },
  {
    id: 9,
    img: require('../Assets/Foods/momos.png'),
    text: 'Momos',
    link: 'Kouser',
  },
  {
    id: 10,
    img: require('../Assets/Foods/muttonfry.png'),
    text: 'Mutton Fry',
    link: 'farsa',
  },
  {
    id: 11,
    img: require('../Assets/Foods/noodles.png'),
    text: 'Noodels',
    link: 'Nahdi',
  },
  {
    id: 12,
    img: require('../Assets/Foods/pasta.png'),
    text: 'Pasta',
    link: 'albaik',
  },
  {
    id: 13,
    img: require('../Assets/Foods/pizza.png'),
    text: 'Pizza',
    link: 'Kouser',
  },
  {
    id: 14,
    img: require('../Assets/Foods/shawarma.png'),
    text: 'Shawarma',
    link: 'farsa',
  },
  {
    id: 15,
    img: require('../Assets/Foods/soup.png'),
    text: 'Soup',
    link: 'Malbar',
  },
  {
    id: 16,
    img: require('../Assets/Foods/cola.png'),
    text: 'Cola',
    link: 'Berry',
  },
];

export const hotel = [
  {
    id: 1,
    hotelimg: require('../Assets/Hotel/farsa.jpg'),
    hotelname: 'Farsa Hotel',
    rating: require('../../Zomotto/Icons/star.png'),
    timer: require('../../Zomotto/Icons/timer.png'),
    detail: 'Fast Food ◉ Bevarages ◉ ₹100 for One ',
    distance: '27 min ◉ 1 km',
    rate: '3.5',
    discount: require('../Icons/discount.png'),
    offer: '40% OFF up to ₹100 ',
    link: 'farsa',
  },

  {
    id: 2,
    hotelimg: require('../Assets/Hotel/albaik.jpg'),
    hotelname: 'Albaik Hotel',
    rating: require('../../Zomotto/Icons/star.png'),
    timer: require('../../Zomotto/Icons/timer.png'),
    detail: 'Fast Food ◉ Bevarages ◉ ₹200 for One ',
    distance: '17 min ◉ 500 mtr',
    rate: '4.5',
    discount: require('../Icons/discount.png'),
    offer: '20% OFF up to ₹500 ',
    link: 'albaik',
  },

  {
    id: 3,
    hotelimg: require('../Assets/Hotel/berry.jpg'),
    hotelname: 'Berry Que ',
    rating: require('../../Zomotto/Icons/star.png'),
    timer: require('../../Zomotto/Icons/timer.png'),
    detail: 'Fast Food ◉ Bar ◉ ₹100 for One ',
    distance: '47 min ◉ 12 km',
    rate: '4.2',
    discount: require('../Icons/discount.png'),
    offer: '10% OFF up to ₹100 ',
    link: 'Berry',
  },

  {
    id: 4,
    hotelimg: require('../Assets/Hotel/kouser.jpg'),
    hotelname: 'Kouser Mandhi',
    rating: require('../../Zomotto/Icons/star.png'),
    timer: require('../../Zomotto/Icons/timer.png'),
    detail: 'Fast Food ◉ Bevarages ◉ ₹150 for One ',
    distance: '10 min ◉ 1 km',
    rate: '4.8',
    discount: require('../Icons/discount.png'),
    offer: '50% OFF up to ₹1000 ',
    link: 'Kouser',
  },

  {
    id: 5,
    hotelimg: require('../Assets/Hotel/malbar.jpg'),
    hotelname: 'Malabar ',
    rating: require('../../Zomotto/Icons/star.png'),
    timer: require('../../Zomotto/Icons/timer.png'),
    detail: 'Fast Food ◉ Bar ◉ ₹500 for One ',
    distance: '7 min ◉ 200 mtr',
    rate: '5.0',
    discount: require('../Icons/discount.png'),
    offer: '10% OFF up to ₹500 ',
    link: 'Malbar',
  },

  {
    id: 6,
    hotelimg: require('../Assets/Hotel/nahdi.jpg'),
    hotelname: 'Nahdi Mandhi ',
    rating: require('../../Zomotto/Icons/star.png'),
    timer: require('../../Zomotto/Icons/timer.png'),
    detail: 'Fast Food ◉ Hotel ◉ ₹190 for One ',
    distance: '20 min ◉ 4 km',
    rate: '4.5',
    discount: require('../Icons/discount.png'),
    offer: '10% OFF up to ₹500 ',
    link: 'Nahdi',
  },

  {
    id: 7,
    hotelimg: require('../Assets/Hotel/midway.jpg'),
    hotelname: 'Midway Hotel ',
    rating: require('../../Zomotto/Icons/star.png'),
    timer: require('../../Zomotto/Icons/timer.png'),
    detail: 'Fast Food ◉ Hotel ◉ ₹190 for One ',
    distance: '10 min ◉ 2 km',
    rate: '4.8',
    discount: require('../Icons/discount.png'),
    offer: '20% OFF up to ₹700 ',
    link: 'Midway',
  },
];

export const farsa = [
  {
    id: 1,
    item: 'Rice and Biriyani',
    foodimg: require('../Assets/Hotel/Farsa/biriyani.jpg'),
    food: 'Biryani',
    rating: '86 Rating',
    price: 120,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Biryani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
    cat: 'biriyani',
  },
  {
    cat: 'biriyani',

    id: 2,
    item: 'Rice and Biriyani',
    foodimg: require('../Assets/Hotel/Farsa/beef.jpg'),
    food: ' Beef Biryani',
    rating: '126 Rating',
    price: 100,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Biryani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'broast',
    id: 3,
    item: 'Fried',
    foodimg: require('../Assets/Hotel/Farsa/broast.jpg'),
    food: 'Broast',
    rating: '546 Rating',
    price: 400,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Biryani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'food',
    id: 4,
    item: 'Dosa',
    foodimg: require('../Assets/Hotel/Farsa/masala.webp'),
    food: 'Masala Dosa',
    rating: '16 Rating',
    price: 60,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/greendot.png'),
    description:
      'Biryani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
];

export const albaik = [
  {
    cat: 'biriyani',
    id: 5,
    item: ' Biriyani',
    foodimg: require('../Assets/Hotel/Albaik/biri.jpeg'),
    food: '  Biryani',
    rating: '126 Rating',
    price: 150,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Biryani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'biriyani',
    id: 6,
    item: ' Biriyani',
    foodimg: require('../Assets/Hotel/Albaik/beeef.jpg'),
    food: ' Beef Biryani',
    rating: '1k Rating',
    price: 180,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Beef Biriyani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'broast',
    id: 7,
    item: 'Broast',
    foodimg: require('../Assets/Hotel/Albaik/broast.webp'),
    food: 'Broast',
    rating: '6k Rating',
    price: 400,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Broast is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'food',
    id: 8,
    item: 'Snack',
    foodimg: require('../Assets/Hotel/Albaik/sandwich.jpg'),
    food: 'Sandwich',
    rating: '1k Rating',
    price: 60,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Sandwich is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
];

export const midway = [
  {
    cat: 'mandhi',
    id: 9,
    item: ' Mandhi',
    foodimg: require('../Assets/Hotel/Midway/mandhi.jpg'),
    food: '  Mandhi',
    rating: '16k Rating',
    price: 580,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Mandhi is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'mandhi',
    id: 10,
    item: '  Mandhi',
    foodimg: require('../Assets/Hotel/Midway/beef.jpeg'),
    food: ' Beef Mandhi',
    rating: '31k Rating',
    price: 780,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Mandhi is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'mandhi',
    id: 11,
    item: ' Mandhi',
    foodimg: require('../Assets/Hotel/Midway/mutton.jpg'),
    food: 'Mutton Mandhi',
    rating: '26k Rating',
    price: 800,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Mutton Mandhi is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'broast',
    id: 12,
    item: 'Chicken',
    foodimg: require('../Assets/Hotel/Midway/alfam.jpg'),
    food: 'Alfam',
    rating: '1M Rating',
    price: 130,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Alfam is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
];

export const berry = [
  {
    cat: 'broast',
    id: 13,
    item: ' Chicken',
    foodimg: require('../Assets/Hotel/Berry/shava.jpg'),
    food: '  Shawaya',
    rating: '20k Rating',
    price: 380,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Shawaya is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'broast',
    id: 14,
    item: '  Chicken',
    foodimg: require('../Assets/Hotel/Berry/alf.jpeg'),
    food: ' Alfam',
    rating: '31k Rating',
    price: 490,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Alfam is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'food',
    id: 15,
    item: ' Mutton',
    foodimg: require('../Assets/Hotel/Berry/kab.webp'),
    food: 'Kabab',
    rating: '126k Rating',
    price: 800,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Kabab is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'food',
    id: 16,
    item: 'Fish',
    foodimg: require('../Assets/Hotel/Berry/fish.jpg'),
    food: 'Fish Fry',
    rating: '1K Rating',
    price: 150,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Fish is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
];

export const malbar = [
  {
    cat: 'biriyani',
    id: 17,
    item: 'Rice and Biriyani',
    foodimg: require('../Assets/Hotel/Farsa/biriyani.jpg'),
    food: 'Biryani',
    rating: '86 Rating',
    price: 120,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Biriyani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'biriyani',
    id: 18,
    item: 'Rice and Biriyani',
    foodimg: require('../Assets/Hotel/Farsa/beef.jpg'),
    food: ' Beef Biryani',
    rating: '126 Rating',
    price: 100,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Beef Biriyani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'broast',
    id: 19,
    item: 'Fried',
    foodimg: require('../Assets/Hotel/Farsa/broast.jpg'),
    food: 'Broast',
    rating: '546 Rating',
    price: 400,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Broast is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'food',
    id: 20,
    item: 'Dosa',
    foodimg: require('../Assets/Hotel/Farsa/masala.webp'),
    food: 'Masala Dosa',
    rating: '16 Rating',
    price: 60,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/greendot.png'),
    description:
      'Dosa is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
];

export const nahdi = [
  {
    cat: 'biriyani',
    id: 21,
    item: ' Biriyani',
    foodimg: require('../Assets/Hotel/Albaik/biri.jpeg'),
    food: '  Biryani',
    rating: '126 Rating',
    price: 150,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Biriyani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'biriyani',
    id: 22,
    item: ' Biriyani',
    foodimg: require('../Assets/Hotel/Albaik/beeef.jpg'),
    food: ' Beef Biryani',
    rating: '1k Rating',
    price: 180,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Beef Biriyani is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'broast',
    id: 23,
    item: 'Broast',
    foodimg: require('../Assets/Hotel/Albaik/broast.webp'),
    food: 'Broast',
    rating: '6k Rating',
    price: 400,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Broast is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'food',
    id: 24,
    item: 'Snack',
    foodimg: require('../Assets/Hotel/Albaik/sandwich.jpg'),
    food: 'Sandwich',
    rating: '1k Rating',
    price: 60,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Sandwich is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
];

export const kouser = [
  {
    cat: 'mandhi',
    id: 25,
    item: ' Mandhi',
    foodimg: require('../Assets/Hotel/Midway/mandhi.jpg'),
    food: '  Mandhi',
    rating: '16k Rating',
    price: 580,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Mandhi is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'mandhi',
    id: 26,
    item: '  Mandhi',
    foodimg: require('../Assets/Hotel/Midway/beef.jpeg'),
    food: ' Beef Mandhi',
    rating: '31k Rating',
    price: 780,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Beef Mandhi is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'mandhi',
    id: 27,
    item: ' Mandhi',
    foodimg: require('../Assets/Hotel/Midway/mutton.jpg'),
    food: 'Mutton Mandhi',
    rating: '26k Rating',
    price: 800,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Mutton Mandhi is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
  {
    cat: 'broast',
    id: 28,
    item: 'Chicken',
    foodimg: require('../Assets/Hotel/Midway/alfam.jpg'),
    food: 'Alfam',
    rating: '1M Rating',
    price: 130,
    star: require('../Assets/Hotel/Insideicons/stars.png'),
    type: require('../Assets/Hotel/Insideicons/leg.png'),
    description:
      'Alfam is known for its aroma and flavor. Fresh herbs, saffron, and basmati rice give it a sweet-floral aroma that hits the nose before you taste it  Whole garam masala, fried onions, and marinated meat provide warmth and subtle heat to the dish. Overall, it tastes like a savory, spiced rice pilaf',
  },
];
